# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt-get install libleptonica-dev libtesseract-dev tesseract-ocr-all -y
      pip3 install opencv-python pytesseract
    command: |
      sudo apt-get install libleptonica-dev libtesseract-dev tesseract-ocr-all -y
      pip3 install opencv-python pytesseract

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
